### ISSUE TITLE
CT impossible set state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#116]
```
balancing-act : phet-io-state-fuzz : require.js : run
Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/assert/js/assert.js?bust=1581949333316:22:13)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioStateEngine.js?bust=1581949333536:278:17)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioStateEngine.js?bust=1581949333536:176:35)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioStateEngine.js?bust=1581949333536:182:9)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioEngineIO.js?bust=1581949333536:203:45)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:236:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:147:38
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:145:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:88:18
id: Bayes Chrome
Approximately 2/17/2020, 6:54:04 AM
balancing-act : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/assert/js/assert.js?bust=1581949333316:22:13)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioStateEngine.js?bust=1581949333536:278:17)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioStateEngine.js?bust=1581949333536:176:35)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioStateEngine.js?bust=1581949333536:182:9)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/PhetioEngineIO.js?bust=1581949333536:203:45)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:236:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:147:38
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:145:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/phet-io/js/phetioCommandProcessor.js?bust=1581949333536:88:18
id: Bayes Chrome
Approximately 2/17/2020, 6:54:04 AM
balancing-act : phet-io-studio-fuzz : require.js : run
Uncaught Error: Assertion failed: no sound found for provided value
Error: Assertion failed: no sound found for provided value
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/assert/js/assert.js?bust=1581952075297:22:13)
    at ScreenSelectionSoundGenerator.playAssociatedSound (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/tambo/js/sound-generators/MultiClip.js?bust=1581952075422:87:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/tambo/js/sound-generators/ScreenSelectionSoundGenerator.js?bust=1581952075422:56:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/TinyEmitter.js?bust=1581952075422:68:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:279:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/joist/js/ScreenButton.js?bust=1581952075422:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/TinyEmitter.js?bust=1581952075422:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Emitter.js?bust=1581952075422:36:31
id: Bayes Chrome
Approximately 2/17/2020, 6:54:04 AM
balancing-act : phet-io-studio-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: no sound found for provided value
Error: Assertion failed: no sound found for provided value
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/assert/js/assert.js?bust=1581952075297:22:13)
    at ScreenSelectionSoundGenerator.playAssociatedSound (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/tambo/js/sound-generators/MultiClip.js?bust=1581952075422:87:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/tambo/js/sound-generators/ScreenSelectionSoundGenerator.js?bust=1581952075422:56:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/TinyEmitter.js?bust=1581952075422:68:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:279:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/joist/js/ScreenButton.js?bust=1581952075422:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/TinyEmitter.js?bust=1581952075422:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Emitter.js?bust=1581952075422:36:31
id: Bayes Chrome
Approximately 2/17/2020, 6:54:04 AM
balancing-act : phet-io-studio-fuzz : require.js : run
Uncaught Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/assert/js/assert.js?bust=1581952075297:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:276:17)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/joist/js/ScreenButton.js?bust=1581952075422:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/TinyEmitter.js?bust=1581952075422:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Emitter.js?bust=1581952075422:36:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Action.js?bust=1581952075422:232:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Emitter.js?bust=1581952075422:61:21)
    at FireListener.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/scenery/js/listeners/FireListener.js?bust=1581952075422:98:25)
id: Bayes Chrome
Approximately 2/17/2020, 6:54:04 AM
balancing-act : phet-io-studio-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/assert/js/assert.js?bust=1581952075297:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:276:17)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Property.js?bust=1581952075422:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/joist/js/ScreenButton.js?bust=1581952075422:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/TinyEmitter.js?bust=1581952075422:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Emitter.js?bust=1581952075422:36:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Action.js?bust=1581952075422:232:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/axon/js/Emitter.js?bust=1581952075422:61:21)
    at FireListener.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1581947644084/scenery/js/listeners/FireListener.js?bust=1581952075422:98:25)
id: Bayes Chrome
Approximately 2/17/2020, 6:54:04 AM
balancing-act : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 2/17/2020, 6:54:04 AM
```

**Comment by KatieWoe** [comment]
```
balancing-act : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_4
Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_4
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/assert/js/assert.js?bust=1582608494695:22:13)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/PhetioStateEngine.js?bust=1582608494864:278:17)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/PhetioStateEngine.js?bust=1582608494864:176:35)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/PhetioStateEngine.js?bust=1582608494864:182:9)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/PhetioEngineIO.js?bust=1582608494864:203:45)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/phetioCommandProcessor.js?bust=1582608494864:267:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/phetioCommandProcessor.js?bust=1582608494864:161:38
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/phetioCommandProcessor.js?bust=1582608494864:159:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/phet-io/js/phetioCommandProcessor.js?bust=1582608494864:102:18
id: Bayes Chrome
Approximately 2/24/2020, 4:53:21 PM
balancing-act : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: no sound found for provided value
Error: Assertion failed: no sound found for provided value
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/assert/js/assert.js?bust=1582624566500:22:13)
    at ScreenSelectionSoundGenerator.playAssociatedSound (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/tambo/js/sound-generators/MultiClip.js?bust=1582624566690:87:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/tambo/js/sound-generators/ScreenSelectionSoundGenerator.js?bust=1582624566690:56:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/TinyEmitter.js?bust=1582624566690:68:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582624566690:279:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582624566690:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582624566690:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/joist/js/ScreenButton.js?bust=1582624566690:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/TinyEmitter.js?bust=1582624566690:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Emitter.js?bust=1582624566690:36:31
id: Bayes Chrome
Approximately 2/24/2020, 4:53:21 PM
balancing-act : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/assert/js/assert.js?bust=1582624566500:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582624566690:276:17)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582624566690:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582624566690:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/joist/js/ScreenButton.js?bust=1582624566690:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/TinyEmitter.js?bust=1582624566690:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Emitter.js?bust=1582624566690:36:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Action.js?bust=1582624566690:227:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Emitter.js?bust=1582624566690:61:21)
    at FireListener.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/scenery/js/listeners/FireListener.js?bust=1582624566690:98:25)
id: Bayes Chrome
Approximately 2/24/2020, 4:53:21 PM
balancing-act : phet-io-studio-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: no sound found for provided value
Error: Assertion failed: no sound found for provided value
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/assert/js/assert.js?bust=1582594459831:22:13)
    at ScreenSelectionSoundGenerator.playAssociatedSound (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/tambo/js/sound-generators/MultiClip.js?bust=1582594459907:87:17)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/tambo/js/sound-generators/ScreenSelectionSoundGenerator.js?bust=1582594459907:56:14
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/TinyEmitter.js?bust=1582594459907:68:55)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582594459907:279:27)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582594459907:178:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Property.js?bust=1582594459907:349:34)
    at ScreenButton.model.selectedScreenProperty.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/joist/js/ScreenButton.js?bust=1582594459907:111:59)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/TinyEmitter.js?bust=1582594459907:68:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1582588401784/axon/js/Emitter.js?bust=1582594459907:36:31
id: Bayes Chrome
Approximately 2/24/2020, 4:53:21 PM
balancing-act : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 2/24/2020, 4:53:21 PM
balancing-act : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 2/24/2020, 4:53:21 PM
```

**Comment by KatieWoe** [comment]
```
balancing-act : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=balancing-act&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_4
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_5
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_6
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_7
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_8
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_9
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_10
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_11
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_12
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_13
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_14
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_15
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_16
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_17
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_18
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_19
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_20
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_21
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_22
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_23
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_24
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_25
Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_4
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_5
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_6
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_7
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_8
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_9
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_10
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_11
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_12
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_13
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_14
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_15
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_16
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_17
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_18
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_19
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_20
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_21
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_22
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_23
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_24
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_25
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584931027006:22:13)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:280:15)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:176:33)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:182:7)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioEngineIO.js:200:43)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:264:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:158:36
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:156:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:99:16
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
balancing-act : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=balancing-act&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_4
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_5
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_6
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_7
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_8
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_9
Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_4
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_5
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_6
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_7
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_8
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_9
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584955081592:22:13)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:280:15)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:176:33)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:182:7)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioEngineIO.js:200:43)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:264:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:158:36
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:156:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:99:16
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
balancing-act : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/state/?sim=balancing-act&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
Error: Assertion failed: Impossible set state:
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_0
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_1
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_2
balancingAct.balanceLabScreen.model.brickStackGroup.brickStack_3
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/assert/js/assert.js?bust=1584966465967:22:13)
    at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:280:15)
    at setStateOnce (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:176:33)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioStateEngine.js:182:7)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/PhetioEngineIO.js:200:43)
    at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:264:51)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:158:36
    at Array.map (<anonymous>)
    at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:156:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io/js/phetioCommandProcessor.js:99:16
id: Bayes Chrome
Approximately 3/22/2020, 5:53:10 PM
balancing-act : phet-io-tests : assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/phet-io-wrappers-tests.html?sim=balancing-act&phetioDebug
9 out of 9 tests passed. 0 failed.

Approximately 3/22/2020, 5:53:10 PM
balancing-act : phet-io-tests : no-assert
https://bayes.colorado.edu/continuous-testing/snapshot-1584921190996/phet-io-wrappers/phet-io-wrappers-tests.html?sim=balancing-act
9 out of 9 tests passed. 0 failed.

Approximately 3/22/2020, 5:53:10 PM
```

**Comment by zepumph** [comment]
State is not supported for this sim, and it is an expected error until we work on this sim again.

**Comment by jbphet** [comment]
I'm not comfortable with this, since I'm the responsible dev for this sim, and as far as I know there is no plan to work on the sim again any time in the future.  That means that there will be CT failures for months, which would mask any *real* errors with the sim.  We should either have some easy way to turn off this test for a given sim or to stub out state support.

**Comment by samreid** [comment]
At today's developer meeting, we talked about the need to remove certain tests or phet-io features from sims.  @zepumph was going to create a phet-io issue.

**Comment by jessegreenberg** [comment]
@zepumph if https://github.com/phetsims/phet-io/issues/1635 is resolved can this be closed?

**Comment by zepumph** [comment]
We now have `perennial/data/phet-io-state-unsupported`, see https://github.com/phetsims/phet-io/issues/1635. Balancing Act is no longer tested for state. closing
