### ISSUE TITLE
CT cannot read property transformMatrix of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#123]
```
balancing-act : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'transformMatrix' of null
TypeError: Cannot read property 'transformMatrix' of null
at wh.beforeCanvasFill (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:546918)
at Object.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:534656)
at wh.canvasPaintSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:552648)
at wh.renderToCanvasSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:460921)
at wh.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:461019)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:461434
at Hb.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:461938)
at oS.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:461943)
at Ba.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:461943)
at Ba.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet/balancing-act_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605250712791%7D&fuzz&memoryLimit=1000:882:461943)
id: Bayes Chrome
Snapshot from 11/12/2020, 8:32:18 PM

----------------------------------

balancing-act : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'transformMatrix' of null
TypeError: Cannot read property 'transformMatrix' of null
at Ba.beforeCanvasFill (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:554229)
at Object.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:541943)
at Ba.canvasPaintSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:559976)
at Ba.renderToCanvasSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:467908)
at Ba.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:468008)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:468423
at aV.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:468931)
at fb.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:468936)
at Jr.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:468936)
at Jr.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/build/phet-io/balancing-act_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605251511992%7D&fuzz&memoryLimit=1000&phetioStandalone:878:468936)
id: Bayes Chrome
Snapshot from 11/12/2020, 8:32:18 PM

----------------------------------

balancing-act : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605242669295%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'transformMatrix' of null
TypeError: Cannot read property 'transformMatrix' of null
at Path.beforeCanvasFill (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Paintable.js:675:24)
at Object.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/display/drawables/PathCanvasDrawable.js:37:14)
at Path.canvasPaintSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Path.js:459:34)
at Path.renderToCanvasSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4409:12)
at Path.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4425:10)
at CarouselButton.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4444:17)
at MassCarousel.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at Node.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at Node.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at BalanceLabView.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
id: Bayes Chrome
Snapshot from 11/12/2020, 8:32:18 PM

----------------------------------

balancing-act : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605262865786%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'transformMatrix' of null
TypeError: Cannot read property 'transformMatrix' of null
at Path.beforeCanvasFill (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Paintable.js:675:24)
at Object.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/display/drawables/PathCanvasDrawable.js:37:14)
at Path.canvasPaintSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Path.js:459:34)
at Path.renderToCanvasSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4409:12)
at Path.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4425:10)
at CarouselButton.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4444:17)
at MassCarousel.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at Node.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at Node.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at BalanceLabView.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
id: Bayes Chrome
Snapshot from 11/12/2020, 8:32:18 PM

----------------------------------

balancing-act : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/phet-io-wrappers/mirror-inputs/?sim=balancing-act&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605238338387%22%2C%22timestamp%22%3A1605258382807%7D
Uncaught Error: Cannot read property 'transformMatrix' of null
TypeError: Cannot read property 'transformMatrix' of null
at Path.beforeCanvasFill (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Paintable.js:675:24)
at Object.paintCanvas (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/display/drawables/PathCanvasDrawable.js:37:14)
at Path.canvasPaintSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Path.js:459:34)
at Path.renderToCanvasSelf (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4409:12)
at Path.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4425:10)
at CarouselButton.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4444:17)
at MassCarousel.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at Node.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at Node.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
at BalanceLabView.renderToCanvasSubtree (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605238338387/scenery/js/nodes/Node.js:4474:17)
id: Bayes Chrome
Snapshot from 11/12/2020, 8:32:18 PM
```

**Comment by jbphet** [comment]
This can be duplicated on an unbuilt version with a fuzz test, though it takes a while.  After examining the state and the stack, I found that the problem can be caused manually be the following sequence:

- Open the sim
- Select the "Balance Lab" screen
- From the PhET menu, select "Screenshot"

**Comment by jbphet** [comment]
I was able to fix this by changing the value of the option of `buttonDisabledColor` from `null` to `Color.TRANSPARENT`.  I'm not sure why this worked or if it is indicative of a more general issue, but it definitely seems odd.  Assigning to @jonathanolson to have a look and decide if something else should be done, since this is related to Scenery rendering.

**Comment by jbphet** [comment]
For reference, here's a stack trace of the issue before it was resolved when running from a non-built version:

```
beforeCanvasFill (Paintable.js:675)
paintCanvas (PathCanvasDrawable.js:37)
canvasPaintSelf (Path.js:459)
renderToCanvasSelf (Node.js:4409)
renderToCanvasSubtree (Node.js:4425)
renderToCanvasSubtree (Node.js:4444)
renderToCanvasSubtree (Node.js:4474)
renderToCanvasSubtree (Node.js:4474)
renderToCanvasSubtree (Node.js:4474)
renderToCanvasSubtree (Node.js:4474)
renderToCanvasSubtree (Node.js:4474)
renderToCanvasSubtree (Node.js:4474)
generateScreenshot (ScreenshotGenerator.js:42)
callback (PhetMenu.js:225)
fire (MenuItem.js:115)
emit (TinyEmitter.js:71)
(anonymous) (Emitter.js:35)
execute (Action.js:225)
emit (Emitter.js:60)
fire (FireListener.js:93)
(anonymous) (FireListener.js:145)
onRelease (PressListener.js:628)
execute (Action.js:225)
release (PressListener.js:413)
release (FireListener.js:138)
pointerUp (PressListener.js:738)
dispatchToListeners (Input.js:1822)
dispatchEvent (Input.js:1776)
upEvent (Input.js:1558)
Input.mouseUpAction.Action.phetioPlayback (Input.js:280)
execute (Action.js:225)
mouseUp (Input.js:1105)
mouseToggle (InputFuzzer.js:266)
InputFuzzer.mouseToggleAction (InputFuzzer.js:40)
fuzzEvents (InputFuzzer.js:105)
fuzzInputEvents (Sim.js:1040)
runAnimationLoop (Sim.js:991)
requestAnimationFrame (async)
```

**Comment by jonathanolson** [comment]
It looks like ButtonNode has disabledColor (which this gets forwarded to) is documented as `// Color when disabled`, presumably it should be changed to support an arbitrary ColorDef.

**Comment by jonathanolson** [comment]
My commit is stalling out (haven't debugged that, looks like hooks are messing up again). Changeset of this seems to work nicely:

```
Jonathans-MacBook-Pro:~/phet/git/sun # git diff --staged js/buttons/ButtonNode.js 
diff --git a/js/buttons/ButtonNode.js b/js/buttons/ButtonNode.js
index 84ff5f40..13cfbc96 100644
--- a/js/buttons/ButtonNode.js
+++ b/js/buttons/ButtonNode.js
@@ -94,7 +94,7 @@ class ButtonNode extends Node {
         }
       },
 
-      // Color when disabled
+      // {ColorDef} - Color when disabled
       disabledColor: ColorConstants.LIGHT_GRAY,
 
       // pdom
@@ -122,9 +122,16 @@ class ButtonNode extends Node {
     // @private - Support baseColor being effected by enabled, while still allowing setting the base color.
     this._settableBaseColorProperty = new PaintColorProperty( options.baseColor );
 
+    // @private
+    this._disabledColorProperty = new PaintColorProperty( options.disabledColor );
+
     // Make the base color into a Property so that the appearance strategy can update itself if changes occur.
-    this.baseColorProperty = new DerivedProperty( [ this._settableBaseColorProperty, this.enabledProperty ], ( color, enabled ) => {
-      return enabled ? color : options.disabledColor;
+    this.baseColorProperty = new DerivedProperty( [
+      this._settableBaseColorProperty,
+      this.enabledProperty,
+      this._disabledColorProperty
+    ], ( color, enabled, disabledColor ) => {
+      return enabled ? color : disabledColor;
     } ); // @private
 
     // @private {PressListener}
`

**Comment by jonathanolson** [comment]
Forced the commit with no verification. @jbphet does this look good?

**Comment by jbphet** [comment]
Looks reasonable to me, and I changed the disabled color back to null in `MassCarousel`, and it worked fine.  Closing.
