### ISSUE TITLE
CT Item not found in Array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#126]
```
balancing-act : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612537046153%22%2C%22timestamp%22%3A1612538341675%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/axon/js/createObservableArray.js:345:33)
at BalanceLabModel.removeMass (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/balancing-act/js/common/model/BalanceModel.js:95:19)
at removeMass (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/balancing-act/js/balancelab/model/BalanceLabModel.js:99:43)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/axon/js/TinyEmitter.js:85:42)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/axon/js/Property.js:289:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/axon/js/Property.js:187:14)
at Boy.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/balancing-act/js/common/model/Mass.js:141:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612537046153/balancing-act/js/common/model/BalanceModel.js:62:12
id: Bayes Chrome
Snapshot from 2/5/2021, 7:57:26 AM
```

**Comment by jbphet** [comment]
To duplicate manually:

- go to the 2nd screen (Balance Lab)
- pull something out of the carousel with a finger, anything will do, but something big makes it easier
- drag the item to a location where it won't fall onto the plank when dropped
- with a second finger, do a zoom-in sort of maneuver on the dragged out thing, i.e. have two fingers on it and spread them out
- lift both fingers at once

I think this is related to https://github.com/phetsims/balancing-act/issues/95, and I think that the best way for me to address it is to update all of the drag handlers to the most recent versions.  I've been avoiding this because of the time involved, but I think this tips the scale towards doing it.

**Comment by pixelzoom** [comment]
In 2/4/21 dev meeting, we established that this is due to multi-touch fuzz testing (` ?fuzzPointers=2`) being enabled for https://github.com/phetsims/aqua/issues/106.  area-builder, balancing-act, fractions-equality, and fractions-intro are all experiencing this problem. So whoever works on this, please consider your fix in the context of all of these sims.

**Comment by jbphet** [comment]
I replaced the old-style drag listener, based on `SimpleDragHandler`, with the updated `DragListener` throughout the sim and then changed the model element creator nodes to use event forwarding instead of having a separate drag listener.  After doing this, I can no longer duplicate the problem following the sequence described above, and several minutes of multi-touch fuzz testing runs with no problems.

I'll check CT after ~24 hours and, if it's clear, I'll close this.

**Comment by jbphet** [comment]
CT is clear.  I'm inclined to close, but @pixelzoom said:

> [P]lease consider your fix in the context of all of these sims.

The fix for this was essentially to update all the drag listeners to the latest and to use event forwarding for the "creator" pattern.  I'll mark this for a quick PSA in dev meeting in case it would be of benefit.

**Comment by pixelzoom** [comment]
2/25/21 dev meeting:

@jbphet gave a PSA, looks like it's applicable to fractions. Closing.
