### ISSUE TITLE
CT Bounds mismatch after validateBounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#141]
```
balancing-act : fuzz : unbuilt : assertSlow
http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702384804032%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/assert/js/assert.js:28:13)
at assertSlow (Node.ts:1564:22)
at (Node.ts:1570:10)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyStaticProperty.ts:67:19)
at link (ImageMassNode.js:100:29)
at (MassNodeFactory.js:27:17)
at createMassNode (BasicBalanceScreenView.js:119:39)
at Proxy.forEach
at forEach (BasicBalanceScreenView.js:148:19)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702382192164%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702384804032%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702382192164%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702384804032%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702384804032%7D&brand=phet&eall&fuzz
[CONSOLE] enabling assert
[CONSOLE] enabling assertSlow
[CONSOLE] Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
[PAGE ERROR] Error: Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/scenery/js/nodes/Node.js:1316:23
at Image.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/scenery/js/nodes/Node.js:1317:9)
at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
at TinyStaticProperty.link (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/axon/js/TinyStaticProperty.js:60:19)
at new ImageMassNode (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/ImageMassNode.js:93:30)
at Object.createMassNode (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/MassNodeFactory.js:25:18)
at handleMassAdded (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/BasicBalanceScreenView.js:109:40)
at Proxy.forEach (<anonymous>)
at new BasicBalanceScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/BasicBalanceScreenView.js:132:20)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 12/12/2023, 4:56:32 AM

----------------------------------

balancing-act : fuzz : unbuilt : assertSlow
http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702389274631%7D&brand=phet&eall&fuzz
Query: brand=phet&eall&fuzz
Uncaught Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/assert/js/assert.js:28:13)
at assertSlow (Node.ts:1564:22)
at (Node.ts:1570:10)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyStaticProperty.ts:67:19)
at link (ImageMassNode.js:100:29)
at (MassNodeFactory.js:27:17)
at createMassNode (BasicBalanceScreenView.js:119:39)
at Proxy.forEach
at forEach (BasicBalanceScreenView.js:148:19)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702382192164%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702389274631%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702382192164%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26eall%26fuzz&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702389274631%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1702382192164%22%2C%22timestamp%22%3A1702389274631%7D&brand=phet&eall&fuzz
[CONSOLE] enabling assert
[CONSOLE] enabling assertSlow
[CONSOLE] Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
[PAGE ERROR] Error: Error: Assertion failed: Bounds mismatch after validateBounds: [x:(-16.1578125,16.1578125),y:(0,52.5)], expected: [x:(-14.875000000000002,14.875000000000002),y:(0,52.5)]. This could have happened if a bounds instance owned by a Node was directly mutated (e.g. bounds.erode())
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/scenery/js/nodes/Node.js:1316:23
at Image.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/scenery/js/nodes/Node.js:1317:9)
at TinyStaticProperty.get (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/axon/js/TinyStaticProperty.js:26:10)
at TinyStaticProperty.link (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/axon/js/TinyStaticProperty.js:60:19)
at new ImageMassNode (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/ImageMassNode.js:93:30)
at Object.createMassNode (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/MassNodeFactory.js:25:18)
at handleMassAdded (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/BasicBalanceScreenView.js:109:40)
at Proxy.forEach (<anonymous>)
at new BasicBalanceScreenView (http://128.138.93.172/continuous-testing/ct-snapshots/1702382192164/chipper/dist/js/balancing-act/js/common/view/BasicBalanceScreenView.js:132:20)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 12/12/2023, 4:56:32 AM
```

**Comment by jbphet** [comment]
Assigning to @Luisav1, since she was making some commits in `ImageMassNode` yesterday and I'm seeing it in the stack trace and also seeing a lot of console logging from this class when I run the fuzz test locally.

**Comment by Luisav1** [comment]
Sorry, I might have changed the `ImageNode` bounds in `ImageMassNode` when creating / modifying the pointer areas.

I wasn't able to reproduce this locally with fuzzing. In the commit above I'm now using a copy of `ImageNode` bounds. I'll wait until CT tests run to completion overnight to see if this issue comes up again.

**Comment by Luisav1** [comment]
In the commit above I'm using `imageNode.bounds.copy();` to obtain the `imageNode`'s bounds wherever necessary instead of its `boundsProperty`. 
This seems to have fixed the issue since this hasn't come up in CT for the past 2 days. Closing.
