### ISSUE TITLE
CT: Negative spacing more than a cell's size causes issues with layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#149]
Occurring sporatically. Looks like it might have started around 1/27/2024 @ 12:58PM.

```
balancing-act : phet-io-multi-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/phet-io-wrappers/multi/?sim=balancing-act&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706567312583%22%2C%22timestamp%22%3A1706568189079%7D
Error: Assertion failed: Negative spacing more than a cell's size causes issues with layout
window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/assert/js/assert.js:28:13)
at assert (FlowConstraint.ts:289:18)
at forEach (FlowConstraint.ts:274:17)
at forEach (FlowConstraint.ts:233:10)
at layout (LayoutConstraint.ts:201:13)
at updateLayout (LayoutConstraint.ts:215:11)
at (TinyEmitter.ts:123:18)
at emit (TinyStaticProperty.ts:56:9)
at notifyListeners (Node.ts:1514:30)
at onAccessAttempt (TinyStaticProperty.ts:31:9)
at get (TinyProperty.ts:52:16)
at (Node.ts:1984:4)
at getBounds (Node.ts:1991:16)
at (LayoutProxy.ts:71:4)
at (LayoutProxy.ts:94:4)
at massLabel (BrickStackNode.js:93:10)
at apply (ManualConstraint.ts:81:26)
at layout (LayoutConstraint.ts:201:13)
at updateLayout (LayoutConstraint.ts:215:11)
at updateLayoutAutomatically (LayoutCell.ts:57:44)
at (TransformTracker.ts:111:21)
at notifyListeners (TransformTracker.ts:122:9)
at onTransformChange (TransformTracker.ts:60:13)
at (TinyEmitter.ts:123:18)
at emit (Node.ts:2803:26)
at (TinyEmitter.ts:123:18)
at emit (Transform3.js:102:23)
at invalidate (Transform3.js:155:9)
at append (Node.ts:2712:20)
at appendMatrix (Node.ts:2442:15)
at scale (Node.ts:2430:13)
at scale (Node.ts:2843:11)
at updateMaxDimension (Node.ts:1451:13)
at validateBounds (Node.ts:1388:16)
at validateBounds (Node.ts:1388:16)
at validateBounds (Node.ts:1626:18)
at watchedBoundsScan (Node.ts:1633:38)
at watchedBoundsScan (Node.ts:1633:38)
at watchedBoundsScan (Node.ts:1633:38)
at watchedBoundsScan (Node.ts:1633:38)
at watchedBoundsScan (Node.ts:1633:38)
at watchedBoundsScan (Node.ts:1612:17)
at validateWatchedBounds (Display.ts:545:19)
at updateDisplay (Sim.ts:436:21)
at apply (PhetioAction.ts:162:16)
at execute (Sim.ts:1023:30)
at stepSimulation (Sim.ts:1013:11)
at stepOneFrame (Sim.ts:988:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
[URL] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1706567312583%2Fphet-io-wrappers%2Fmulti%2F%3Fsim%3Dbalancing-act%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=60000&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706567312583%22%2C%22timestamp%22%3A1706568189079%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1706567312583%2Fphet-io-wrappers%2Fmulti%2F%3Fsim%3Dbalancing-act%26locales%3D*%26phetioWrapperDebug%3Dtrue%26fuzz%26phetioDebug%3Dtrue&duration=60000&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706567312583%22%2C%22timestamp%22%3A1706568189079%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/phet-io-wrappers/multi/?sim=balancing-act&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706567312583%22%2C%22timestamp%22%3A1706568189079%7D
[ATTACHED]
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/balancing-act/balancing-act_en.html?brand=phet-io&ea&postMessageOnError&sim=balancing-act&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706567312583%22%2C%22timestamp%22%3A1706568189079%7D&frameTitle=sim1
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/balancing-act/balancing-act_en.html?brand=phet-io&ea&postMessageOnError&sim=balancing-act&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22phet-io-multi-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706567312583%22%2C%22timestamp%22%3A1706568189079%7D&frameTitle=sim2
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706567312583/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: Negative spacing more than a cell's size causes issues with layout
[PAGE ERROR] Error: Assertion failed: Negative spacing more than a cell's size causes issues with layout
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error
[PAGE ERROR] Error: Error: Assertion failed: Negative spacing more than a cell's size causes issues with layout

id: "Sparky Node Firefox"
Snapshot from 1/29/2024, 3:28:32 PM
```

**Comment by jbphet** [comment]
I tried for about an hour to duplicate this and/or track down the problem, but haven't had any luck.  The problem is originating at a `ManualConstraint` in `BrickStackNode`.  According the the GitHub log, this code was added by @marlitas within the last month, so I'm going to turn this over to her to see if she can offer any insights.

**Comment by jbphet** [comment]
@marlitas - I set up a number of tests to try to duplicate this, and took a look at a bunch of the translations to see if I could get some insights into why this is happening.  If knowing what I did would be helpful, let me know and we can set up a time to discuss.

**Comment by jbphet** [comment]
Just after writing up my previous comment I had a thought that I should try to duplicate it with `stringTest=dynamic`.  The problem can be duplicated with this test by putting a brick stack on the plank in the 2nd screen and then pressing the down arrow.  This is great, but because I'm not that fluent in layout constraints, I'm still not sure how to resolve the problem.  I can see that it's being caused by switching from a taller piece of text to a shorter one, but I'm not sure why this leads to a problem.

**Comment by marlitas** [comment]
Thanks for the investigation @jbphet. I will bundle this into some Balancing Act work I will be doing next week.

**Comment by marlitas** [comment]
@jonathanolson helped me fix this and keep some of that reduced spacing in the brick stack labels by overriding local bounds. @amanda-phet can you check that the vertical label spacing looks good to you for the brick stacks? It'll be a little different from the published version now, but if it's really bothersome I can do some more work in the code to get it closer. 

<img width="97" alt="image" src="https://github.com/phetsims/balancing-act/assets/42476338/b1d28527-2fa4-428d-8741-3666c02eb58c">

**Comment by amanda-phet** [comment]
I think it looks just fine!
