### ISSUE TITLE
CT should not be called if disposed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balancing-act#151]
```
balancing-act : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709129691886%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at assert (TinyEmitter.ts:99:14)
at emit (TinyProperty.ts:125:9)
at notifyListeners (TinyProperty.ts:73:11)
at set (TinyForwardingProperty.ts:179:12)
at set (Node.ts:4207:27)
at setPickable (Node.ts:4216:9)
at (BrickStackNode.js:153:71)
at (TinyEmitter.ts:137:42)
at emit (ReadOnlyProperty.ts:334:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709129354130%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709129691886%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709129354130%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709129691886%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709129691886%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 265810
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 2/28/2024, 7:09:14 AM

----------------------------------

balancing-act : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132144940%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at assert (TinyEmitter.ts:99:14)
at emit (TinyProperty.ts:125:9)
at notifyListeners (TinyProperty.ts:73:11)
at set (TinyForwardingProperty.ts:179:12)
at set (Node.ts:4207:27)
at setPickable (Node.ts:4216:9)
at (BrickStackNode.js:153:71)
at (TinyEmitter.ts:137:42)
at emit (ReadOnlyProperty.ts:334:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709129354130%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132144940%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709129354130%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132144940%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132144940%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 182481
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at BrickStackNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at Array.updatePickabilityWhenAnimating (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/BrickStackNode.js:134:21)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:110:39)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 2/28/2024, 7:09:14 AM

----------------------------------

balancing-act : multitouch-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132124729%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at assert (TinyEmitter.ts:99:14)
at emit (TinyProperty.ts:125:9)
at notifyListeners (TinyProperty.ts:73:11)
at set (TinyForwardingProperty.ts:179:12)
at set (Node.ts:4207:27)
at setPickable (Node.ts:4216:9)
at (ImageMassNode.js:177:19)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:334:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709129354130%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132124729%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1709129354130%2Fbalancing-act%2Fbalancing-act_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26fuzzPointers%3D2%26supportsPanAndZoom%3Dfalse&testInfo=%7B%22test%22%3A%5B%22balancing-act%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132124729%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/balancing-act/balancing-act_en.html?continuousTest=%7B%22test%22%3A%5B%22balancing-act%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1709129354130%22%2C%22timestamp%22%3A1709132124729%7D&brand=phet&ea&fuzz&fuzzPointers=2&supportsPanAndZoom=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: should not be called if disposed
[PAGE ERROR] Error: Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/assert/js/assert.js:28:13)
at TinyForwardingProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:74:15)
at TinyForwardingProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:109:10)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyProperty.js:58:12)
at TinyForwardingProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyForwardingProperty.js:141:13)
at ImageMassNode.setPickable (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3908:28)
at set pickable [as pickable] (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/scenery/js/nodes/Node.js:3916:10)
at http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/balancing-act/js/common/view/ImageMassNode.js:162:21
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1709129354130/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 2/28/2024, 7:09:14 AM
```

**Comment by jbphet** [comment]
This assertion is occurring during the `listenerOrder=random` test in CT.  The problem happens if the listeners that are watching for masses to return to the carousel are shuffled in a particular way.  If the listener that removes the mass from the model and scene graph fires before the one that updates the pickability, the latter asserts, essentially saying, "Hey, this is disposed, why is it still being updated?".  I've added a check to prevent the update to pickability if the node has been disposed, and this seems to resolve the problem.

I'll keep an eye on CT and close this issue if it looks clear after a few runs.

**Comment by jbphet** [comment]
CT is clear.  Closing.
