### ISSUE TITLE
CT: reentry detected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balancing-act#86]
Looks like there's a Property somewhere in this sim that needs to be `reentrant: false`.  This happens with rare frequency in CT:

balancing-act : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: reentry detected, value=23, oldValue=22.650000000000034
Error: Assertion failed: reentry detected, value=23, oldValue=22.650000000000034
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/assert/js/assert.js:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:303:19)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:287:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:230:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:336:36)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/balancing-act/js/game/view/MassValueEntryNode.js?bust=1538665930144:82:30)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Emitter.js?bust=1538665930144:181:52)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:306:29)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:287:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1538633413047/axon/js/Property.js?bust=1538665930144:230:16)
Approximately 10/4/2018, 12:10:13 AM

**Comment by KatieWoe** [comment]
CT had been looking fairly clear, but this error popped up again.
```
balancing-act : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: reentry detected, value=26, oldValue=25.650000000000034
Error: Assertion failed: reentry detected, value=26, oldValue=25.650000000000034
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/assert/js/assert.js:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:274:19)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:258:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:201:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:307:36)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/balancing-act/js/game/view/MassValueEntryNode.js?bust=1539662708984:82:30)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Emitter.js?bust=1539662708984:258:52)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:277:29)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:258:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539662708984:201:16)
id: Bayes Chrome
Approximately 10/15/2018, 7:51:17 PM
balancing-act : xss-fuzz : run
Uncaught Error: Assertion failed: reentry detected, value=78, oldValue=78.14999999999964
Error: Assertion failed: reentry detected, value=78, oldValue=78.14999999999964
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/assert/js/assert.js:22:13)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:274:19)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:258:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:201:16)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:307:36)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/balancing-act/js/game/view/MassValueEntryNode.js?bust=1539660198077:82:30)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Emitter.js?bust=1539660198077:258:52)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:277:29)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:258:14)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1539654677810/axon/js/Property.js?bust=1539660198077:201:16)
id: Bayes Chrome
Approximately 10/15/2018, 7:51:17 PM
```

**Comment by pixelzoom** [comment]
Still recurring intermittently as of 11/7/18.

**Comment by jbphet** [comment]
There have been 20 runs on continuous test with no failures since this change, and it was happening fairly often before.  Below is a screenshot that shows two failed runs prior to the fix and 20 successful runs after.  I think it's safe to say that this is fixed, closing.

![image](https://user-images.githubusercontent.com/3082831/49663690-b0596400-fa0c-11e8-853e-dc3d93017988.png)
